config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :index]

  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.position').uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to admin_railway_stations_path, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to admin_railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to [:admin, @route]
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, station], html: { style: "display: #{ hidden ? 'none' : 'block' }" } do |form| %>
  <%= render 'common/errors', resource: station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/railway_stations/_railway_station.html.erb
<% @railway_stations.each do |railway_station| %>
  <tr>
    <td>
      <div id="railway_station_title_<%= railway_station.id %>">
        <%= railway_station.title %>
      </div>
      <%= render 'form', station: railway_station, hidden: true %>
    </td>
    <td><%= link_to 'Show', [:admin, railway_station] %></td>
    <td><%= link_to 'Edit', '', class: 'edit-station', data: { station_id: railway_station.id } %></td>
    <td><%= link_to 'Destroy', [:admin, railway_station], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/admin/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', station: @railway_station %>

<%= link_to 'Show', [:admin, @railway_station] %> |
<%= link_to 'Back', admin_railway_stations_path %>

app/views/admin/railway_stations/index.html.erb
<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'railway_station' %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_admin_railway_station_path %>

app/views/admin/railway_stations/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', station: @railway_station %>

<%= link_to t('common.back'), admin_railway_stations_path %>

app/views/admin/railway_stations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_admin_railway_station_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>