config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :index]

  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, :top_seats, :bottom_seats, presence: true

  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :ordered, -> { order(:number) }
end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
end

app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :side_bottom_seats, :side_top_seats, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.position').uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :route
  belongs_to :railway_station

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name ||= "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, 'Route should contains minimum 2 stations!')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: 'start_station_id'
  belongs_to :finish_station, class_name: 'RailwayStation', foreign_key: 'finish_station_id'

  after_create :send_notification

  def route_name
    "#{start_station.title} - #{finish_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  has_many :carriages
  belongs_to :railway_station
  belongs_to :route
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tickets
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, alert: 'Forbidden! This page only for admins!' unless current_user.admin?
  end
end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_train, only: [:new, :create]

  def index
    @carriages = Carriage.all
  end

  def show
    @carriage = Carriage.find(params[:id])
  end

  def new
    @carriage = Carriage.new
  end

  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  protected

  def set_train
    @train = Train.find(params[:train_id])
  end

  def carriage_params
    params.require(:carriage).permit(:number, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats)
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :destroy, :update]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to [:admin, @route]
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  def set_route
    @route = Route.find(params[:id])
  end

  private

  def route_params
    params.require(:route).permit(railway_station_ids: [])
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :model, :number_of_wagons, :train_type, :railway_station_id, :route_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

  def create
    @stations = RailwayStation.all

    redirect_to search_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    @tickets = current_user.tickets
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = current_user.tickets.new # (must be ticket params)

    if @ticket.save
      redirect_to @ticket
    else
      redirect_to search_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/carriages/new.html.erb
<h1>New Carriage</h1>

<%= form_for [:admin, @train, @carriage] do |form| %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :top_seats %>
    <%= form.number_field :top_seats %>
  </div>

  <div class="field">
    <%= form.label :bottom_seats %>
    <%= form.number_field :bottom_seats %>
  </div>

  <div class="field">
    <%= form.label :side_top_seats %>
    <%= form.number_field :side_top_seats %>
  </div>

  <div class="field">
    <%= form.label :side_bottom_seats %>
    <%= form.number_field :side_bottom_seats %>
  </div>

  <div class="field">
    <%= form.submit 'Create' %>
  </div>

<% end %>

app/views/admin/carriages/show.html.erb
<h1>Carriage № <%= @carriage.number %></h1>

<p>
  Train: <%= @carriage.train.number %>
</p>

<p>
  Top seats: <%= @carriage.top_seats %>
</p>

<p>
  Bottom seats: <%= @carriage.bottom_seats %>
</p>

<p>
  Side top seats: <%= @carriage.side_top_seats %>
</p>

<p>
  Side bottom seats: <%= @carriage.side_bottom_seats %>
</p>

<%= link_to 'Back', [:admin, @carriage.train] %>

app/views/admin/routes/_form.html.erb
<%= form_with(model: [:admin, route], local: true) do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_station_ids %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true, prompt: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/routes/_railway_stations.html.erb
<strong>Railway Stations:</strong>
<table>
  <thead>
  <tr>
    <td width="100px">Title:</td>
    <td>Position:</td>
  </tr>
  </thead>
  <tbody>
    <% @route.railway_stations.ordered.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td>
          <%= form_tag update_position_admin_railway_station_path(railway_station), method: :patch do %>
          <%= number_field_tag :position, railway_station.position_in(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag "Update" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/routes/_routes.html.erb
<% @routes.each do |route| %>
  <tr>
    <td><%= route.name %></td>
    <td><%= link_to 'Show', [:admin, route] %></td>
    <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
    <td><%= link_to 'Destroy', [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/admin/routes/_trains.html.erb
<p>
  <strong>Trains on this route:</strong>
</p>
<table>
  <thead>
  <tr>
    <th>Number</th>
    <th>Model</th>
    <th>Number of wagons</th>
    <th>Train type</th>
  </tr>
  </thead>

  <tbody>
  <% @route.trains.each do |train| %>
    <tr>
      <td><%= train.number %></td>
      <td><%= train.model %></td>
      <td><%= train.number_of_wagons %></td>
      <td><%= train.train_type %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', [:admin, @route] %> |
<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>First Station</th>
      <th>Last Station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'routes' %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<% if @route.railway_stations.present? %>
<p>
  <strong>First Station:</strong>
  <%= @route.railway_stations.first.title %>
</p>

<p>
  <strong>Last Station:</strong>
  <%= @route.railway_stations.last.title %>
</p>
  <%= render 'railway_stations' %>
  <% else %>
  <p>
    <strong>Not Stations!</strong>
  </p>
  <% end %>

<% if @route.trains.present?%>
  <%= render 'trains' %>
<% else %>
  <p>
    <strong>Not trains on this route now!</strong>
  </p>
<% end %>

<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>

app/views/tickets/index.html.erb
<p>All tickets of <%= current_user.email %></p>

<ul>
<% @tickets.each do |ticket| %>
  <li><%= ticket.route_name %></li>
<% end %>
</ul>

app/views/tickets/show.html.erb
<p>This ticket buy user: <%= @ticket.user.email %></p>

app/views/welcome/index.html.erb
<h1>Welcome to Ruby on Rails application!</h1>

<%= link_to "Routes list", admin_routes_path%>
<%= link_to "Stations list", admin_railway_stations_path %>
<%= link_to "Trains list", admin_trains_path %>