config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :index]

  resource :search, only: [:new, :show, :edit, :create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  get 'welcome/index'
  root 'searches#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  has_many :carriages
  belongs_to :railway_station
  belongs_to :route
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :model, :number_of_wagons, :train_type, :railway_station_id, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_with(model: [:admin, train], local: true) do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :number_of_wagons %>
    <%= form.number_field :number_of_wagons %>
  </div>

  <div class="field">
    <%= form.label :train_type %>
    <%= form.text_field :train_type %>
  </div>

  <div class="field">
    <%= form.label :railway_station_id %>
    <%= form.collection_select :railway_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route_id %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/trains/_trains.html.erb
<% @trains.each do |train| %>
  <tr>
    <td><%= train.number %></td>
    <td><%= train.model %></td>
    <td><%= train.number_of_wagons %></td>
    <td><%= train.train_type %></td>
    <td><%= link_to 'Show', [:admin, train] %></td>
    <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
    <td><%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', [:admin, @train] %>
<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Model</th>
      <th>Number of wagons</th>
      <th>Train type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'trains' %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @train.model %>
</p>

<p>
  <strong>Number of wagons:</strong>
  <%= @train.number_of_wagons %>
</p>

<p>
  <strong>Train type:</strong>
  <%= @train.train_type %>
</p>

<% if @train.route.present?%>
  <p>
    <strong>In the route:</strong>
    <%= @train.route.name %>
  </p>
<% else %>
  <p>
    <strong>Not in the route now!</strong>
  </p>
<% end %>

<% if @train.railway_station.present?%>
  <p>
    <strong>On the station:</strong>
    <%= @train.railway_station.title %>
  </p>
<% else %>
  <p>
    <strong>Not on the station now!</strong>
  </p>
<% end %>

<p>
  <strong>Carriages:</strong>
  <ul> <% @train.carriages.each do |carr| %>
    <li><%= link_to "Carriage №#{carr.number}", [:admin, carr] %></li>
      <% end %>
  </ul>
</p>

<p>
  <%= link_to 'Add carriage', new_admin_train_carriage_path(@train) %>
</p>

<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>